"""add_user_auth_fields

Revision ID: 3aa34c8b2163
Revises: c9d8afaa6546
Create Date: 2026-09-05 23:37:10.326134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa34c8b2163'
down_revision: Union[str, Sequence[str], None] = 'c9d8afaa6546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with nullable=True initially to accommodate existing records
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # Populate any existing records (e.g. dev user 1)
    from app.core.security import hash_password
    default_dev_hash = hash_password('password123')
    op.execute(
        sa.text(
            f"UPDATE users SET email = 'dev@example.com', hashed_password = '{default_dev_hash}', name = 'Dev User' WHERE email IS NULL"
        )
    )

    # Enforce non-nullability and uniqueness
    op.alter_column('users', 'email', nullable=False)
    op.alter_column('users', 'hashed_password', nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'name')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
