"""add_news_articles

Revision ID: c9d8afaa6546
Revises: 0c1770a16606
Create Date: 2026-09-05 23:13:01.930735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d8afaa6546'
down_revision: Union[str, Sequence[str], None] = '0c1770a16606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_article_id', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_article_id', 'instrument_id', name='uq_news_article_provider_article_inst')
    )
    op.create_index('ix_news_articles_inst_published', 'news_articles', ['instrument_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_instrument_id'), 'news_articles', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_news_articles_provider_article_id'), 'news_articles', ['provider_article_id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_table('change_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('detected_change_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['detected_change_id'], ['detected_changes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_reviews_detected_change_id'), 'change_reviews', ['detected_change_id'], unique=False)
    op.create_index(op.f('ix_change_reviews_user_id'), 'change_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_reviews_user_id'), table_name='change_reviews')
    op.drop_index(op.f('ix_change_reviews_detected_change_id'), table_name='change_reviews')
    op.drop_table('change_reviews')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_provider_article_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_instrument_id'), table_name='news_articles')
    op.drop_index('ix_news_articles_inst_published', table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
