"""add_significance_assessments

Revision ID: 0c1770a16606
Revises: 93267c7cdea3
Create Date: 2026-09-05 19:53:42.759749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1770a16606'
down_revision: Union[str, Sequence[str], None] = '93267c7cdea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('significance_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detected_change_id', sa.Integer(), nullable=False),
    sa.Column('magnitude_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('abnormality_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('relative_performance_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('volume_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('event_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('significance_level', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detected_change_id'], ['detected_changes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detected_change_id', name='uq_assessment_detected_change')
    )
    op.create_index(op.f('ix_significance_assessments_detected_change_id'), 'significance_assessments', ['detected_change_id'], unique=True)
    op.create_index(op.f('ix_significance_assessments_significance_level'), 'significance_assessments', ['significance_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_significance_assessments_significance_level'), table_name='significance_assessments')
    op.drop_index(op.f('ix_significance_assessments_detected_change_id'), table_name='significance_assessments')
    op.drop_table('significance_assessments')
    # ### end Alembic commands ###
