"""add_user_observations_and_detected_changes

Revision ID: 93267c7cdea3
Revises: 561a8050c69a
Create Date: 2026-09-05 19:19:09.285293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93267c7cdea3'
down_revision: Union[str, Sequence[str], None] = '561a8050c69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detected_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('baseline_observation_id', sa.Integer(), nullable=False),
    sa.Column('current_observation_id', sa.Integer(), nullable=False),
    sa.Column('magnitude', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_observation_id'], ['market_observations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_observation_id'], ['market_observations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'instrument_id', 'baseline_observation_id', 'current_observation_id', 'change_type', name='uq_detected_change_identity')
    )
    op.create_index(op.f('ix_detected_changes_baseline_observation_id'), 'detected_changes', ['baseline_observation_id'], unique=False)
    op.create_index(op.f('ix_detected_changes_change_type'), 'detected_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_detected_changes_current_observation_id'), 'detected_changes', ['current_observation_id'], unique=False)
    op.create_index(op.f('ix_detected_changes_instrument_id'), 'detected_changes', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_detected_changes_user_id'), 'detected_changes', ['user_id'], unique=False)
    op.create_table('user_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_observation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_seen_observation_id'], ['market_observations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'instrument_id', name='uq_user_instrument_observation')
    )
    op.create_index(op.f('ix_user_observations_instrument_id'), 'user_observations', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_user_observations_last_seen_observation_id'), 'user_observations', ['last_seen_observation_id'], unique=False)
    op.create_index(op.f('ix_user_observations_user_id'), 'user_observations', ['user_id'], unique=False)
    op.add_column('watchlists', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlists', 'last_checked_at')
    op.drop_index(op.f('ix_user_observations_user_id'), table_name='user_observations')
    op.drop_index(op.f('ix_user_observations_last_seen_observation_id'), table_name='user_observations')
    op.drop_index(op.f('ix_user_observations_instrument_id'), table_name='user_observations')
    op.drop_table('user_observations')
    op.drop_index(op.f('ix_detected_changes_user_id'), table_name='detected_changes')
    op.drop_index(op.f('ix_detected_changes_instrument_id'), table_name='detected_changes')
    op.drop_index(op.f('ix_detected_changes_current_observation_id'), table_name='detected_changes')
    op.drop_index(op.f('ix_detected_changes_change_type'), table_name='detected_changes')
    op.drop_index(op.f('ix_detected_changes_baseline_observation_id'), table_name='detected_changes')
    op.drop_table('detected_changes')
    # ### end Alembic commands ###
